"""Meldungstexte der Strukturregeln (``BPMN-S…``)."""

from __future__ import annotations

from .severity import ERROR, NOTE, WARNING

TEXTS: tuple[tuple[str, str, str, str, str], ...] = (
    (
        "BPMN-S001",
        ERROR,
        "structure",
        "Das Wurzelelement ist nicht bpmn:definitions im BPMN-2.0-Namensraum.",
        "The root element is not bpmn:definitions in the BPMN 2.0 namespace.",
    ),
    ("BPMN-S002", ERROR, "structure", "Das Dokument enthält keinen Prozess.", "The document contains no process."),
    (
        "BPMN-S003",
        ERROR,
        "structure",
        "Die Element-ID „{id}“ ist mehrfach vergeben.",
        "Element ID '{id}' is used more than once.",
    ),
    (
        "BPMN-S010",
        ERROR,
        "structure",
        "Prozess „{name}“ hat kein Startereignis.",
        "Process '{name}' has no start event.",
    ),
    ("BPMN-S011", ERROR, "structure", "Prozess „{name}“ hat kein Endereignis.", "Process '{name}' has no end event."),
    (
        "BPMN-S012",
        WARNING,
        "structure",
        "„{name}“ ist mit keinem Sequenz- oder Nachrichtenfluss verbunden (verwaist).",
        "'{name}' is not connected by any sequence or message flow (orphaned).",
    ),
    (
        "BPMN-S013",
        WARNING,
        "structure",
        "„{name}“ hat keinen eingehenden Sequenzfluss.",
        "'{name}' has no incoming sequence flow.",
    ),
    (
        "BPMN-S014",
        WARNING,
        "structure",
        "„{name}“ hat keinen ausgehenden Sequenzfluss.",
        "'{name}' has no outgoing sequence flow.",
    ),
    (
        "BPMN-S015",
        ERROR,
        "structure",
        "Startereignis „{name}“ hat einen eingehenden Sequenzfluss.",
        "Start event '{name}' has an incoming sequence flow.",
    ),
    (
        "BPMN-S016",
        ERROR,
        "structure",
        "Endereignis „{name}“ hat einen ausgehenden Sequenzfluss.",
        "End event '{name}' has an outgoing sequence flow.",
    ),
    (
        "BPMN-S020",
        ERROR,
        "structure",
        "Sequenzfluss „{id}“ ist nicht verbunden (Quelle oder Ziel fehlt).",
        "Sequence flow '{id}' is not connected (source or target missing).",
    ),
    (
        "BPMN-S021",
        ERROR,
        "structure",
        "Sequenzfluss „{id}“ verweist auf das unbekannte Element „{ref}“.",
        "Sequence flow '{id}' refers to unknown element '{ref}'.",
    ),
    (
        "BPMN-S022",
        ERROR,
        "structure",
        "Sequenzfluss „{id}“ überschreitet die Grenze eines Prozesses oder Unterprozesses.",
        "Sequence flow '{id}' crosses a process or sub-process boundary.",
    ),
    (
        "BPMN-S023",
        ERROR,
        "structure",
        "Nachrichtenfluss „{id}“ verbindet Elemente desselben Pools.",
        "Message flow '{id}' connects elements of the same pool.",
    ),
    (
        "BPMN-S024",
        ERROR,
        "structure",
        "Nachrichtenfluss „{id}“ ist nicht verbunden oder verweist auf ein unbekanntes Element.",
        "Message flow '{id}' is not connected or refers to an unknown element.",
    ),
    (
        "BPMN-S030",
        WARNING,
        "structure",
        "Gateway „{name}“ hat bedingte ausgehende Flüsse, aber keinen Default-Fluss.",
        "Gateway '{name}' has conditional outgoing flows but no default flow.",
    ),
    (
        "BPMN-S031",
        ERROR,
        "structure",
        "Der Default-Fluss „{flow}“ von „{name}“ ist kein ausgehender Fluss dieses Elements.",
        "Default flow '{flow}' of '{name}' is not an outgoing flow of this element.",
    ),
    (
        "BPMN-S032",
        NOTE,
        "structure",
        "Gateway „{name}“ verzweigt ohne Bedingungen und ohne Default-Fluss.",
        "Gateway '{name}' splits without conditions and without a default flow.",
    ),
    (
        "BPMN-S033",
        NOTE,
        "structure",
        "Gateway „{name}“ hat genau einen Ein- und einen Ausgang und ist entbehrlich.",
        "Gateway '{name}' has exactly one incoming and one outgoing flow and is redundant.",
    ),
    (
        "BPMN-S034",
        ERROR,
        "structure",
        "Ereignisbasiertes Gateway „{name}“ führt zu „{ziel}“; "
        "zulässig sind nur fangende Zwischenereignisse und Empfangsaufgaben.",
        "Event-based gateway '{name}' leads to '{ziel}'; "
        "only catching intermediate events and receive tasks are allowed.",
    ),
    (
        "BPMN-S035",
        ERROR,
        "structure",
        "Paralleles Gateway „{name}“ hat bedingte ausgehende Flüsse.",
        "Parallel gateway '{name}' has conditional outgoing flows.",
    ),
    (
        "BPMN-S040",
        ERROR,
        "structure",
        "Randereignis „{name}“ hat keinen ausgehenden Sequenzfluss.",
        "Boundary event '{name}' has no outgoing sequence flow.",
    ),
    (
        "BPMN-S041",
        ERROR,
        "structure",
        "Randereignis „{name}“ hat einen eingehenden Sequenzfluss.",
        "Boundary event '{name}' has an incoming sequence flow.",
    ),
    (
        "BPMN-S042",
        ERROR,
        "structure",
        "Randereignis „{name}“ ist an keine bekannte Aktivität angeheftet.",
        "Boundary event '{name}' is not attached to a known activity.",
    ),
    ("BPMN-S050", WARNING, "structure", "Aufgabe „{id}“ hat keinen Namen.", "Task '{id}' has no name."),
    (
        "BPMN-S051",
        NOTE,
        "structure",
        "Verzweigendes Gateway „{id}“ hat keine Beschriftung (Frage).",
        "Splitting gateway '{id}' has no label (question).",
    ),
    (
        "BPMN-S060",
        WARNING,
        "structure",
        "Link-Wurfereignis „{name}“ (Link „{link}“) hat kein passendes Fangereignis im Diagramm.",
        "Link throw event '{name}' (link '{link}') has no matching catch event in the diagram.",
    ),
    (
        "BPMN-S061",
        WARNING,
        "structure",
        "Aufrufaktivität „{name}“ nennt kein aufgerufenes Element.",
        "Call activity '{name}' names no called element.",
    ),
    (
        "BPMN-S070",
        ERROR,
        "structure",
        "Datenassoziation „{id}“ verweist auf das unbekannte Element „{ref}“.",
        "Data association '{id}' refers to unknown element '{ref}'.",
    ),
    (
        "BPMN-S071",
        ERROR,
        "structure",
        "Assoziation „{id}“ verweist auf das unbekannte Element „{ref}“.",
        "Association '{id}' refers to unknown element '{ref}'.",
    ),
)
