"""Meldungstexte der fachlichen Regeln (``BPMN-F…``)."""

from __future__ import annotations

from .severity import ERROR, NOTE, WARNING

TEXTS: tuple[tuple[str, str, str, str, str], ...] = (
    ("BPMN-F001", NOTE, "content", "Aufgabe „{name}“ hat keine Rechtsgrundlage.", "Task '{name}' has no legal basis."),
    (
        "BPMN-F002",
        WARNING,
        "content",
        "Das Diagramm hat keine Diagramm-Infos (flowaudit:diagrammInfo).",
        "The diagram has no diagram information (flowaudit:diagrammInfo).",
    ),
    (
        "BPMN-F003",
        WARNING,
        "content",
        "Die Diagramm-Infos nennen keinen Status.",
        "The diagram information states no status.",
    ),
    (
        "BPMN-F004",
        ERROR,
        "content",
        "Der Status „{wert}“ ist unbekannt (zulässig: {zulaessig}).",
        "Status '{wert}' is unknown (allowed: {zulaessig}).",
    ),
    (
        "BPMN-F005",
        WARNING,
        "content",
        "Die Gültigkeit ist am {datum} abgelaufen (Stichtag {stichtag}).",
        "Validity expired on {datum} (reference date {stichtag}).",
    ),
    (
        "BPMN-F006",
        NOTE,
        "content",
        "Die Gültigkeit beginnt erst am {datum} (Stichtag {stichtag}).",
        "Validity only starts on {datum} (reference date {stichtag}).",
    ),
    (
        "BPMN-F007",
        ERROR,
        "content",
        "„gültig ab“ ({ab}) liegt nach „gültig bis“ ({bis}).",
        "'Valid from' ({ab}) is after 'valid until' ({bis}).",
    ),
    (
        "BPMN-F008",
        WARNING,
        "content",
        "Das Diagramm ist freigegeben, aber Freigabe durch oder am fehlt.",
        "The diagram is approved, but approver or approval date is missing.",
    ),
    (
        "BPMN-F009",
        ERROR,
        "content",
        "Das Feld „{feld}“ enthält kein gültiges Datum (JJJJ-MM-TT): „{wert}“.",
        "Field '{feld}' does not contain a valid date (YYYY-MM-DD): '{wert}'.",
    ),
    (
        "BPMN-F010",
        WARNING,
        "content",
        "Die strukturierte Rechtsgrundlage an „{name}“ nennt keine Norm.",
        "The structured legal basis at '{name}' names no legal act.",
    ),
    (
        "BPMN-F011",
        WARNING,
        "content",
        "Das Kennzeichen „{typ}“ an „{name}“ ist unbekannt.",
        "Marker '{typ}' at '{name}' is unknown.",
    ),
    (
        "BPMN-F012",
        WARNING,
        "content",
        "„{name}“ trägt das Kennzeichen Rechtsgrundlage, hat aber keine Rechtsgrundlage.",
        "'{name}' carries the legal-basis marker but has no legal basis.",
    ),
    (
        "BPMN-F013",
        WARNING,
        "content",
        "Die Farbe „{wert}“ in „{feld}“ ist keine #RRGGBB-Angabe.",
        "Colour '{wert}' in '{feld}' is not a #RRGGBB value.",
    ),
    (
        "BPMN-F014",
        WARNING,
        "content",
        "Der Fonds „{wert}“ ist im Profil „{profil}“ nicht vorgesehen.",
        "Fund '{wert}' is not provided for in profile '{profil}'.",
    ),
    (
        "BPMN-F015",
        WARNING,
        "content",
        "Die Förderperiode „{wert}“ passt nicht zum Profil „{profil}“ ({periode}).",
        "Programming period '{wert}' does not match profile '{profil}' ({periode}).",
    ),
    (
        "BPMN-F016",
        WARNING,
        "content",
        "Das Profil „{wert}“ ist unbekannt; geprüft wird mit „{profil}“.",
        "Profile '{wert}' is unknown; checking with '{profil}'.",
    ),
    (
        "BPMN-F017",
        WARNING,
        "content",
        "Der Wert „{wert}“ im Feld „{feld}“ ist unbekannt (zulässig: {zulaessig}).",
        "Value '{wert}' in field '{feld}' is unknown (allowed: {zulaessig}).",
    ),
    (
        "BPMN-F018",
        NOTE,
        "content",
        "Das Ist-Diagramm nennt kein Soll-Diagramm (bezugDiagramm).",
        "The actual-state diagram names no target diagram (bezugDiagramm).",
    ),
    ("BPMN-F020", NOTE, "content", "{art} „{name}“ hat keine Akteur-Rolle.", "{art} '{name}' has no actor role."),
    (
        "BPMN-F021",
        WARNING,
        "content",
        "Die Rolle „{rolle}“ an „{name}“ ist im Profil „{profil}“ unbekannt.",
        "Role '{rolle}' at '{name}' is unknown in profile '{profil}'.",
    ),
    (
        "BPMN-F022",
        NOTE,
        "content",
        "Die Rolle „{rolle}“ ({bezeichnung}) an „{name}“ ist für die Förderperiode {periode} nicht vorgesehen.",
        "Role '{rolle}' ({bezeichnung}) at '{name}' is not provided for in programming period {periode}.",
    ),
    (
        "BPMN-F023",
        ERROR,
        "content",
        "Die Kernanforderung „{ka}“ an „{name}“ ist im Katalog „{profil}“ nicht enthalten (vorhanden: {vorhanden}).",
        "Key requirement '{ka}' at '{name}' is not in catalogue '{profil}' (available: {vorhanden}).",
    ),
    (
        "BPMN-F024",
        ERROR,
        "content",
        "Das Bewertungskriterium „{bk}“ an „{name}“ passt nicht zur Kernanforderung {ka} (erwartet „{ka}.…“).",
        "Assessment criterion '{bk}' at '{name}' does not match key requirement {ka} (expected '{ka}.…').",
    ),
    (
        "BPMN-F025",
        WARNING,
        "content",
        "Das Bewertungskriterium „{bk}“ an „{name}“ ist im Katalog nicht enthalten.",
        "Assessment criterion '{bk}' at '{name}' is not in the catalogue.",
    ),
    (
        "BPMN-F026",
        WARNING,
        "content",
        "Die Prüfart „{wert}“ an „{name}“ ist unbekannt.",
        "Audit type '{wert}' at '{name}' is unknown.",
    ),
    (
        "BPMN-F027",
        WARNING,
        "content",
        "Der Verweis an „{name}“ hat die unbekannte Art „{wert}“ oder keinen Schlüssel.",
        "The reference at '{name}' has unknown type '{wert}' or no key.",
    ),
)
