"""Profile descriptions for the web API: rules, parameters and input fields.

Everything here is read-only and framework-free. Input fields come from the
packaged ``field_catalog.json`` (generated by ``tools/export_field_catalog.py``
from the same derivation as ``docs/eingabefelder.md``).
"""

from __future__ import annotations

import json
import math
from collections.abc import Mapping
from functools import cache
from importlib import resources
from typing import TypedDict, cast

from ..profiles import RiskProfile, Rule, available_profiles, load_profile
from .jsontypes import JsonObject, JsonValue, json_object, json_safe

CATALOG_SCHEMA = "auditcore_risk.field-catalog/1"
#: Parameter keys that name input fields, not settings (``field``, ``amount_field`` …).
_FIELD_SUFFIXES = ("field", "fields")
#: Substitutes for missing data are behaviour, not thresholds.
_NOT_PARAMETERS = ("missing_value",)
_SOURCE_KEYS = ("repository", "path", "commit", "symbols", "decision", "derived_from", "rights")


class FieldUse(TypedDict):
    """How one rule reads a field and what happens when it is absent or empty."""

    code: str
    label: str
    role: str
    absent: str
    empty: str


class FieldEntry(TypedDict):
    """One input field of a profile (see ``docs/eingabefelder.md``)."""

    name: str
    meaning: str | None
    meaning_source: str | None
    requirement: str
    required_by: list[str]
    value_required_by: list[str]
    uses: list[FieldUse]


class ProfileCatalog(TypedDict):
    """Catalog entry of one profile version."""

    fingerprint: str
    input_contract: str | None
    fields: list[FieldEntry]


class Catalog(TypedDict):
    """The packaged ``field_catalog.json``."""

    schema: str
    generated_by: str
    undocumented: str
    profiles: dict[str, ProfileCatalog]


@cache
def field_catalog() -> Catalog:
    """The packaged field catalog (``profiles`` keyed by ``<id>@<version>``)."""
    text = resources.files(__package__).joinpath("field_catalog.json").read_text("utf-8")
    data = cast(Catalog, json.loads(text))
    if data.get("schema") != CATALOG_SCHEMA:
        raise RuntimeError("field_catalog.json hat ein unbekanntes Schema.")
    return data


def profile_fields(profile: RiskProfile) -> list[FieldEntry]:
    """Input fields of ``profile`` with meaning, requirement and missing-data behaviour."""
    entry = field_catalog()["profiles"].get(f"{profile.id}@{profile.version}")
    if entry is None or entry["fingerprint"] != profile.fingerprint:
        return []
    return list(entry["fields"])


def rule_inputs(profile: RiskProfile) -> dict[str, list[str]]:
    """Per rule code the input fields it reads (catalog order)."""
    out: dict[str, list[str]] = {r.code: [] for r in profile.rules}
    for field in profile_fields(profile):
        for use in field["uses"]:
            names = out.get(use["code"])
            if names is not None and field["name"] not in names:
                names.append(field["name"])
    return out


def _is_number(value: object) -> bool:
    return isinstance(value, int | float) and not isinstance(value, bool) and math.isfinite(value)


def _numeric(value: object) -> bool:
    if _is_number(value):
        return True
    return isinstance(value, list | tuple) and bool(value) and all(_is_number(v) for v in value)


def rule_parameters(params: Mapping[str, object], prefix: str = "") -> JsonObject:
    """Numeric settings of a rule (thresholds, factors, limits) as dotted keys.

    Field names and substitutes for missing values are left out; lists of
    numbers (e.g. national value limits) stay lists.
    """
    out: JsonObject = {}
    for key, value in params.items():
        name = f"{prefix}{key}"
        if isinstance(value, Mapping):
            out.update(rule_parameters(value, f"{name}."))
        elif key.endswith(_FIELD_SUFFIXES) or key.endswith(_NOT_PARAMETERS):
            continue
        elif _numeric(value):
            out[name] = json_safe(value)
    return out


def rule_view(rule: Rule, inputs: list[str]) -> JsonObject:
    """Display description of one rule."""
    return {
        "code": rule.code,
        "label": rule.label,
        "kind": rule.kind,
        "scope": rule.scope,
        "severity": rule.severity,
        "interpretation": rule.interpretation,
        "note": rule.note,
        "requires": list[JsonValue](rule.requires),
        "when_missing_columns": rule.when_missing_columns,
        "column": rule.column,
        "points": rule.points,
        "inputs": list[JsonValue](inputs),
        "parameters": rule_parameters(rule.params),
        "params": json_safe(rule.params),
        "origin": json_safe(rule.origin),
    }


def rules_view(profile: RiskProfile) -> list[JsonValue]:
    """All rules of ``profile`` in profile order."""
    inputs = rule_inputs(profile)
    return [rule_view(rule, inputs[rule.code]) for rule in profile.rules]


def profile_summary(profile: RiskProfile) -> JsonObject:
    """Short entry for the profile list."""
    return {
        **profile.reference,
        "kind": profile.kind,
        "legal_status": profile.legal_status,
        "rule_count": len(profile.rules),
        "field_count": len(profile_fields(profile)),
        "open_decision_count": len(profile.open_decisions),
    }


def list_profiles() -> list[JsonValue]:
    """Every packaged rule profile (id and version sorted)."""
    return [profile_summary(load_profile(pid, version)) for pid, version in available_profiles()]


def profile_detail(profile: RiskProfile) -> JsonObject:
    """Full profile description: identity, source, rules and input fields."""
    source = {k: profile.source[k] for k in _SOURCE_KEYS if k in profile.source}
    assessment = profile.assessment
    return {
        **profile_summary(profile),
        "source": json_object(source),
        "input_contract": json_safe(profile.source.get("input_contract")),
        "open_decisions": list[JsonValue](profile.open_decisions),
        "output": json_object(profile.output),
        "summary_format": json_safe(profile.summary.get("format")),
        "assessment": None if assessment is None else json_safe(assessment.get("kind")),
        "rules": rules_view(profile),
        "fields": json_safe(profile_fields(profile)),
    }
