export { default as FaGeoMap } from './FaGeoMap.vue'
export { geoMapElement } from './element'
export { useGeoMap, type GeoBusy, type GeoHint, type GeoMapCallbacks, type UseGeoMap } from './useGeoMap'
/** Kern (Vertrag auditcore_geo.web, Modell, Port, Kartenansicht, Zustandsautomat) aus `@auditcore/ui-core`. */
export {
  geoMessages,
  TOLERANCE_STEPS,
  parseDegrees,
  parseLatLon,
  parseMetres,
  parseUtm,
  utmErrorKey,
  formatDistance,
  formatDegrees,
  formatMetres,
  vertexCount,
  areasFromGeoPackage,
  displayName,
  type CoordinateError,
  type UtmInput,
  type UtmInputError,
  createGeoRestPort,
  type GeoRestOptions,
} from '@auditcore/ui-core'
export type {
  LatLon,
  AreaGeometry,
  GeoPoint,
  GeoArea,
  TileSource,
  EarthModel,
  GeoCatalogue,
  RadiusRequest,
  RadiusHit,
  RadiusResult,
  Position,
  LocateRequest,
  DegenerateRing,
  LocateResult,
  UtmRequest,
  UtmResult,
  UtmPointRequest,
  UtmPointResult,
  SimplifyUnit,
  SimplifyRequest,
  SimplifyResult,
  GeoPackageArea,
  GeoPackageResult,
  GeocodeHit,
  GeocodeResult,
  GeoPort,
} from '@auditcore/ui-core'
