"""Kandidatenlisten und feste Konstanten für echt wirkende Ersatzwerte."""

from __future__ import annotations

FIRST_NAMES: tuple[str, ...] = (
    "Thomas",
    "Andrea",
    "Martin",
    "Claudia",
    "Stefan",
    "Birgit",
    "Jonas",
    "Elena",
    "Kristin",
    "Pawel",
    "Marek",
    "Ilona",
    "Henrik",
    "Sofia",
    "Lukas",
    "Marta",
    "Daniel",
    "Regina",
    "Anton",
    "Nadja",
    "Peter",
    "Helena",
    "Vincent",
    "Tereza",
    "Oskar",
    "Miriam",
    "Fabian",
    "Judith",
    "Roland",
    "Beatrix",
)

LAST_NAMES: tuple[str, ...] = (
    "Berger",
    "Lindqvist",
    "Hartmann",
    "Novak",
    "Weidner",
    "Kovács",
    "Ahrens",
    "Brandt",
    "Dorsch",
    "Ehrlich",
    "Falk",
    "Gerlach",
    "Haller",
    "Imhoff",
    "Jansen",
    "Kestner",
    "Lohmann",
    "Meinhardt",
    "Nolte",
    "Osterloh",
    "Pfeiffer",
    "Quandt",
    "Reinders",
    "Sturm",
    "Tillmann",
    "Ulrich",
    "Vogler",
    "Wendler",
    "Zimmerer",
    "Amann",
    "Bregenz",
    "Cordes",
    "Deichmann",
    "Ebner",
    "Fassbender",
    "Grothe",
    "Hövel",
    "Isenberg",
    "Jörgensen",
    "Kruse",
)

COMPANY_PREFIXES: tuple[str, ...] = (
    "Nordwerk",
    "Südanker",
    "Ostrand",
    "Weststeg",
    "Bergblick",
    "Talgrund",
    "Waldkante",
    "Seeblick",
    "Steinfeld",
    "Lindenhof",
    "Ahornbach",
    "Kranichsee",
    "Falkenstein",
    "Hafenblick",
    "Moorbach",
    "Uferland",
    "Kiesgrund",
    "Rauental",
    "Silberbach",
    "Wiesenhof",
)

COMPANY_SUFFIXES: tuple[str, ...] = (
    "Technik",
    "Systeme",
    "Bau",
    "Plan",
    "Service",
    "Logistik",
    "Handel",
    "Projekt",
    "Energie",
    "Verfahren",
    "Anlagen",
    "Werkstoffe",
    "Montage",
    "Beratung",
    "Analytik",
    "Elektronik",
    "Umwelt",
    "Prozess",
    "Maschinen",
    "Fertigung",
)

LEGAL_FORMS: tuple[str, ...] = (
    "GmbH & Co. KG",
    "UG (haftungsbeschränkt)",
    "Sp. z o.o.",
    "gGmbH",
    "GmbH",
    "mbH",
    "KGaA",
    "OHG",
    "GbR",
    "e. V.",
    "e.V.",
    "AG",
    "KG",
    "eG",
    "SE",
    "S.p.A.",
    "S.r.l.",
    "S.A.",
    "B.V.",
    "N.V.",
    "Kft.",
    "Zrt.",
    "Oy",
    "A/S",
    "Ltd.",
    "LLC",
    "Inc.",
)

EMAIL_DOMAIN: str = "example"
PHONE_PREFIX: str = "+49 30"
PHONE_BLOCK: str = "23125"
NULL_BANK_CODE_DE: str = "00000000"

IBAN_LENGTHS: dict[str, int] = {
    "AT": 20,
    "BE": 16,
    "BG": 22,
    "CH": 21,
    "CY": 28,
    "CZ": 24,
    "DE": 22,
    "DK": 18,
    "EE": 20,
    "ES": 24,
    "FI": 18,
    "FR": 27,
    "GR": 27,
    "HR": 21,
    "HU": 28,
    "IE": 22,
    "IS": 26,
    "IT": 27,
    "LI": 21,
    "LT": 20,
    "LU": 20,
    "LV": 21,
    "MT": 31,
    "NL": 18,
    "NO": 15,
    "PL": 28,
    "PT": 25,
    "RO": 24,
    "SE": 24,
    "SI": 19,
    "SK": 24,
}
