"""Constraint lock for CI installs (``requirements/ci.lock``).

The internal packages (``auditcore``, ``auditcore_*``) are built from this
repository and are not on PyPI, so the lock covers only third-party
requirements: the input ``requirements/ci.in`` lists every runtime and optional
requirement of the platform and all domain packages, and ``uv pip compile``
resolves it once for every supported Python version. CI installs with
``uv pip install -c requirements/ci.lock …``; the setuptools packages stay as
they are.

    python scripts/ci_lock.py          # write ci.in and compile ci.lock (needs uv)
    python scripts/ci_lock.py --check  # fail when ci.in is outdated (no network)
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "requirements" / "ci.in"
LOCK = ROOT / "requirements" / "ci.lock"
INTERNAL = re.compile(r"^auditcore([_-][a-z0-9_-]+)?$", re.IGNORECASE)
NAME = re.compile(r"^\s*([A-Za-z0-9_.-]+)")
HEADER = "# Generated by scripts/ci_lock.py – do not edit; run the script instead.\n"


def requirements(pyproject: Path) -> set[str]:
    """Runtime and optional requirements of one project, without internal packages."""
    project = tomllib.loads(pyproject.read_text(encoding="utf-8"))["project"]
    found = set(project.get("dependencies", []))
    for extra in project.get("optional-dependencies", {}).values():
        found.update(extra)
    external = set()
    for requirement in found:
        match = NAME.match(requirement)
        if match and not INTERNAL.match(match.group(1)):
            external.add(" ".join(requirement.split()))
    return external


def render_input(root: Path = ROOT) -> str:
    projects = [root / "pyproject.toml", *sorted(root.glob("packages/*/pyproject.toml"))]
    lines = sorted(set().union(*(requirements(p) for p in projects)), key=str.lower)
    return HEADER + "".join(f"{line}\n" for line in lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="only verify ci.in")
    args = parser.parse_args(argv)
    expected = render_input()
    if args.check:
        current = INPUT.read_text(encoding="utf-8") if INPUT.exists() else ""
        if current != expected:
            print("requirements/ci.in is outdated: run python scripts/ci_lock.py", file=sys.stderr)
            return 1
        return 0
    INPUT.parent.mkdir(exist_ok=True)
    INPUT.write_text(expected, encoding="utf-8")
    command = ["uv", "pip", "compile", str(INPUT), "--universal", "--python-version", "3.11"]
    command += ["--quiet", "--no-header", "--output-file", str(LOCK)]
    subprocess.run(command, check=True, cwd=ROOT)  # noqa: S603
    LOCK.write_text(HEADER + LOCK.read_text(encoding="utf-8"), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
