import { expect, test, type Locator, type Page } from '@playwright/test'

const SHOTS = process.env.FA_SCREENSHOTS

async function openKanban(page: Page): Promise<string[]> {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => {
    if (message.type() === 'error') errors.push(message.text())
  })
  await page.goto('/#/kanban')
  await expect(page.getByRole('heading', { name: 'Vorhabenprüfung 2026' })).toBeVisible()
  return errors
}

const column = (page: Page, id: string): Locator => page.locator(`[data-column-id="${id}"]`)
const card = (page: Page, title: string): Locator => page.locator('.fa-kanban__columns [data-card-id]', { hasText: title })
const status = (page: Page): Locator => page.getByRole('status')

async function drag(page: Page, source: Locator, target: Locator): Promise<void> {
  const from = await source.boundingBox()
  const to = await target.boundingBox()
  if (!from || !to) throw new Error('Element nicht sichtbar')
  await page.mouse.move(from.x + from.width / 2, from.y + 20)
  await page.mouse.down()
  await page.mouse.move(from.x + from.width / 2 + 10, from.y + 30, { steps: 3 })
  await page.mouse.move(to.x + to.width / 2, to.y + to.height - 30, { steps: 12 })
  await page.mouse.up()
}

test('Ziehen mit der Maus verschiebt eine Karte und hält das WIP-Limit ein', async ({ page }) => {
  const errors = await openKanban(page)
  await drag(page, card(page, 'Belegliste Breitbandausbau'), column(page, 'pruefung'))
  await expect(column(page, 'pruefung').locator('[data-card-id]')).toHaveCount(3)
  await expect(status(page)).toContainText('abgelegt in Prüfung')
  await expect(column(page, 'pruefung').locator('.fa-kanban-column__count')).toHaveText('3/3')
  await drag(page, card(page, 'Stichprobe Q3'), column(page, 'pruefung'))
  await expect(column(page, 'pruefung').locator('[data-card-id]')).toHaveCount(3)
  await expect(column(page, 'auswahl').locator('[data-card-id]')).toHaveCount(1)
  if (SHOTS) await page.screenshot({ path: `${SHOTS}/kanban-board.png` })
  expect(errors).toEqual([])
})

test('Tastatur: aufnehmen, verschieben, ablegen und Strg+Pfeil', async ({ page }) => {
  const errors = await openKanban(page)
  const first = card(page, 'Stichprobe Q3')
  await first.focus()
  await page.keyboard.press('Space')
  await expect(status(page)).toContainText('aufgenommen')
  await expect(first).toHaveAttribute('aria-pressed', 'true')
  await page.keyboard.press('ArrowDown')
  await expect(status(page)).toContainText('Position 2 von 2')
  await page.keyboard.press('Space')
  await expect(column(page, 'auswahl').locator('[data-card-id]').last()).toContainText('Stichprobe Q3')
  await expect(card(page, 'Stichprobe Q3')).toBeFocused()
  await page.keyboard.press('Control+ArrowRight')
  await expect(column(page, 'pruefung')).toContainText('Stichprobe Q3')
  await expect(card(page, 'Stichprobe Q3')).toBeFocused()
  await page.keyboard.press('Space')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('Escape')
  await expect(status(page)).toContainText('abgebrochen')
  await expect(column(page, 'pruefung')).toContainText('Stichprobe Q3')
  expect(errors).toEqual([])
})

test('Suche, Prioritätsfilter und Detailansicht mit Bearbeitung', async ({ page }) => {
  const errors = await openKanban(page)
  await page.getByRole('searchbox', { name: 'Suchen' }).fill('vergabe')
  await expect(page.locator('.fa-kanban__columns [data-card-id]')).toHaveCount(1)
  await page.getByRole('button', { name: 'Filter zurücksetzen' }).click()
  await page.getByRole('combobox', { name: 'Priorität' }).selectOption('hoch')
  await expect(page.locator('.fa-kanban__columns [data-card-id]')).toHaveCount(2)
  await page.getByRole('combobox', { name: 'Priorität' }).selectOption('')
  await card(page, 'Vergabeakte').focus()
  await page.keyboard.press('Enter')
  const detail = page.getByRole('dialog')
  await expect(detail).toBeVisible()
  await detail.getByLabel('Titel').fill('Vergabeakte Innovationslabor vollständig sichten')
  await detail.getByLabel('Titel').press('Enter')
  await detail.getByPlaceholder('+ Neuer Eintrag + Enter').fill('Dokumentation')
  await detail.getByPlaceholder('+ Neuer Eintrag + Enter').press('Enter')
  await expect(detail.getByText('1/4 erledigt')).toBeVisible()
  if (SHOTS) await page.screenshot({ path: `${SHOTS}/kanban-detail.png` })
  await detail.getByRole('button', { name: 'Prüfnotiz VP-19 öffnen' }).click()
  await expect(page.getByTestId('demo-last')).toHaveText('navigate → notebook-page:page-vp19')
  await page.keyboard.press('Escape')
  await expect(detail).toBeHidden()
  await expect(card(page, 'vollständig sichten')).toContainText('1/4')
  expect(errors).toEqual([])
})

test('Einstellungen: Spalte anlegen und Karten entfernter Spalten übernehmen', async ({ page }) => {
  const errors = await openKanban(page)
  await page.getByRole('button', { name: 'Board-Einstellungen' }).click()
  const dialog = page.getByRole('dialog', { name: 'Board-Einstellungen' })
  await dialog.getByRole('button', { name: 'Spalte hinzufügen' }).click()
  await dialog.getByRole('button', { name: 'Spalte Entwurf entfernen' }).click()
  await expect(dialog.getByText('Karten entfernter Spalten wandern in die erste Spalte.')).toBeVisible()
  if (SHOTS) await page.screenshot({ path: `${SHOTS}/kanban-einstellungen.png` })
  await dialog.getByTestId('kanban-settings-save').click()
  await expect(dialog).toBeHidden()
  await expect(column(page, 'neue_spalte')).toBeVisible()
  await expect(column(page, 'auswahl')).toContainText('Prüfbericht Gründerzentrum')
  expect(errors).toEqual([])
})

test('Rechte: Leserin sieht nur, Bearbeiter darf verschieben, aber nicht teilen', async ({ page }) => {
  const errors = await openKanban(page)
  await page.getByTestId('demo-user').selectOption('lena')
  await expect(page.getByText('Nur Lesezugriff')).toBeVisible()
  await expect(page.getByRole('button', { name: /Aufgabe hinzufügen/ })).toHaveCount(0)
  await drag(page, card(page, 'Belegliste Breitbandausbau'), column(page, 'pruefung'))
  await expect(column(page, 'auswahl').locator('[data-card-id]')).toHaveCount(2)
  await page.getByTestId('demo-user').selectOption('markus')
  await expect(page.getByRole('button', { name: 'Board teilen' })).toHaveCount(0)
  await drag(page, card(page, 'Belegliste Breitbandausbau'), column(page, 'pruefung'))
  await expect(column(page, 'pruefung').locator('[data-card-id]')).toHaveCount(3)
  expect(errors).toEqual([])
})

test('Teilen: Person suchen, freigeben und Berechtigung ändern', async ({ page }) => {
  const errors = await openKanban(page)
  await page.getByRole('button', { name: 'Board teilen' }).click()
  const dialog = page.getByRole('dialog', { name: 'Board teilen' })
  await dialog.getByRole('searchbox', { name: 'Person suchen' }).fill('Tob')
  await dialog.getByRole('button', { name: /Tobias Keller/ }).click()
  await expect(dialog.locator('[data-share="tobias"]')).toContainText('Tobias Keller')
  await dialog.locator('[data-share="tobias"] select').selectOption('edit')
  await expect(dialog.locator('[data-share="tobias"] select')).toHaveValue('edit')
  if (SHOTS) await page.screenshot({ path: `${SHOTS}/kanban-teilen.png` })
  expect(errors).toEqual([])
})

test('cockpit-Board: nur Eingang ↔ Geplant, „Läuft“ gesperrt', async ({ page }) => {
  const errors = await openKanban(page)
  await page.locator('.fa-kanban-boards__open', { hasText: 'Aufträge (cockpit)' }).click()
  await expect(page.getByRole('heading', { name: 'Aufträge (cockpit)' })).toBeVisible()
  await card(page, 'Repo prüfen').focus()
  await page.keyboard.press('Space')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Space')
  await expect(column(page, 'geplant')).toContainText('Repo prüfen')
  await card(page, 'Sicherheitsprüfung').focus()
  await page.keyboard.press('Control+ArrowLeft')
  await expect(column(page, 'laeuft')).toContainText('Sicherheitsprüfung')
  expect(errors).toEqual([])
})

test('Dunkelmodus und englische Oberfläche', async ({ page }) => {
  const errors = await openKanban(page)
  await page.getByTestId('theme-toggle').click()
  await page.getByTestId('locale-toggle').click()
  await expect(page.getByRole('button', { name: 'Board settings' })).toBeVisible()
  await page.waitForTimeout(300)
  if (SHOTS) await page.screenshot({ path: `${SHOTS}/kanban-dunkel-en.png` })
  expect(errors).toEqual([])
})
