import { describe, expect, it } from 'vitest'

import { getBusinessObject } from '../src'
import { createKit } from './helpers/modeling'

describe('Modellierung: Anlegen und Verbinden', () => {
  it('legt Aufgabe an und verbindet mit Sequenzfluss (semantisch und DI)', async () => {
    const kit = await createKit()
    const start = kit.registry.get('StartEvent_1')
    const task = kit.create('bpmn:Task', 400, 120)
    const flow = kit.modeling.connect(start, task)
    expect(flow.type).toBe('bpmn:SequenceFlow')
    const bo = getBusinessObject(flow)
    expect(bo.sourceRef).toBe(getBusinessObject(start))
    expect(bo.targetRef).toBe(getBusinessObject(task))
    expect(getBusinessObject(start).outgoing).toContain(bo)
    expect(getBusinessObject(task).incoming).toContain(bo)
    const process = getBusinessObject(kit.root())
    expect(process.flowElements).toContain(bo)
    expect(process.flowElements).toContain(getBusinessObject(task))
    const xml = await kit.xml()
    expect(xml).toContain(`<bpmn:sequenceFlow id="${bo.id}" sourceRef="StartEvent_1" targetRef="${task.id}"`)
    expect(xml).toContain(`<bpmndi:BPMNEdge id="${bo.id}_di" bpmnElement="${bo.id}">`)
    expect(flow.waypoints.length).toBeGreaterThanOrEqual(2)
  })

  it('verschiebt, ändert Größe und löscht mit Rückgängig/Wiederholen', async () => {
    const kit = await createKit()
    const task = kit.create('bpmn:Task', 400, 120)
    kit.modeling.moveShape(task, { x: 30, y: 40 })
    expect(task.di.bounds.x).toBe(task.x)
    expect(task.di.bounds.y).toBe(task.y)
    kit.modeling.resizeShape(task, { x: task.x, y: task.y, width: 160, height: 90 })
    expect(task.di.bounds.width).toBe(160)
    kit.modeling.removeShape(task)
    expect(kit.registry.get(task.id)).toBeUndefined()
    expect(getBusinessObject(kit.root()).flowElements).not.toContain(getBusinessObject(task))
    kit.commandStack.undo()
    expect(kit.registry.get(task.id)).toBe(task)
    expect(getBusinessObject(kit.root()).flowElements).toContain(getBusinessObject(task))
    expect(task.di.$parent.planeElement).toContain(task.di)
    kit.commandStack.undo()
    expect(task.di.bounds.width).toBe(100)
    kit.commandStack.redo()
    kit.commandStack.redo()
    expect(kit.registry.get(task.id)).toBeUndefined()
  })

  it('verbindet Vorgänger und Nachfolger beim Löschen eines Zwischenschritts', async () => {
    const kit = await createKit()
    const start = kit.registry.get('StartEvent_1')
    const task = kit.create('bpmn:Task', 400, 120)
    const end = kit.create('bpmn:EndEvent', 600, 120)
    const first = kit.modeling.connect(start, task)
    kit.modeling.connect(task, end)
    kit.modeling.removeShape(task)
    expect(first.target).toBe(end)
    expect(getBusinessObject(first).targetRef).toBe(getBusinessObject(end))
  })

  it('pflegt Standardfluss und bedingten Fluss', async () => {
    const kit = await createKit()
    const gateway = kit.create('bpmn:ExclusiveGateway', 400, 120)
    const a = kit.create('bpmn:Task', 600, 60)
    const b = kit.create('bpmn:Task', 600, 220)
    const toA = kit.modeling.connect(gateway, a)
    const toB = kit.modeling.connect(gateway, b)
    kit.replace.replaceFlow(toA, 'default')
    expect(getBusinessObject(gateway).default).toBe(getBusinessObject(toA))
    kit.replace.replaceFlow(toB, 'conditional')
    expect(getBusinessObject(toB).conditionExpression.$type).toBe('bpmn:FormalExpression')
    kit.modeling.removeConnection(toA)
    expect(getBusinessObject(gateway).default).toBeUndefined()
    kit.commandStack.undo()
    expect(getBusinessObject(gateway).default).toBe(getBusinessObject(toA))
  })

  it('setzt und entfernt Farben (bioc und color)', async () => {
    const kit = await createKit()
    const start = kit.registry.get('StartEvent_1')
    kit.modeling.setColor([start], { fill: '#ffcdd2', stroke: '#b71c1c' })
    expect(start.di.get('bioc:fill')).toBe('#ffcdd2')
    expect(start.di.get('color:background-color')).toBe('#ffcdd2')
    expect(start.di.get('color:border-color')).toBe('#b71c1c')
    const xml = await kit.xml()
    expect(xml).toContain('bioc:stroke="#b71c1c"')
    kit.modeling.setColor([start], { fill: null, stroke: null })
    expect(start.di.get('bioc:fill')).toBeUndefined()
    kit.commandStack.undo()
    expect(start.di.get('bioc:fill')).toBe('#ffcdd2')
  })

  it('ändert Eigenschaften und moddle-Eigenschaften (auch Kennung)', async () => {
    const kit = await createKit()
    const task = kit.create('bpmn:Task', 400, 120)
    kit.modeling.updateProperties(task, { name: 'Prüfen', id: 'Task_Pruefen' })
    expect(kit.registry.get('Task_Pruefen')).toBe(task)
    expect(task.di.id).toBe('Task_Pruefen_di')
    const extension = kit.editor.get<any>('moddle').create('bpmn:ExtensionElements')
    kit.modeling.updateModdleProperties(task, getBusinessObject(task), { extensionElements: extension })
    kit.modeling.updateModdleProperties(task, task.di, { 'bioc:fill': '#eeeeee' })
    expect(task.di.get('bioc:fill')).toBe('#eeeeee')
    kit.commandStack.undo()
    kit.commandStack.undo()
    kit.commandStack.undo()
    expect(kit.registry.get(task.id)).toBe(task)
    expect(getBusinessObject(task).name).toBeUndefined()
  })

  it('legt externe Beschriftungen an, ändert und entfernt sie', async () => {
    const kit = await createKit()
    const start = kit.registry.get('StartEvent_1')
    kit.modeling.updateLabel(start, 'Antrag eingegangen')
    expect(start.label).toBeTruthy()
    expect(start.di.label.bounds.y).toBeGreaterThan(start.y + start.height - 1)
    kit.modeling.moveShape(start.label, { x: 10, y: 10 })
    expect(start.di.label.bounds.x).toBe(start.label.x)
    kit.modeling.updateLabel(start, '')
    expect(start.label).toBeFalsy()
    expect(getBusinessObject(start).name).toBeUndefined()
    kit.commandStack.undo()
    expect(start.label).toBeTruthy()
  })

  it('beschriftet Textanmerkung und Gruppe', async () => {
    const kit = await createKit()
    const note = kit.create('bpmn:TextAnnotation', 400, 300)
    kit.modeling.updateLabel(note, 'Hinweis')
    expect(getBusinessObject(note).text).toBe('Hinweis')
    const group = kit.create('bpmn:Group', 700, 400)
    kit.modeling.updateLabel(group, 'Phase 1')
    expect(getBusinessObject(group).categoryValueRef.value).toBe('Phase 1')
    const xml = await kit.xml()
    expect(xml).toMatch(/<bpmn:category id="[^"]+">\s*<bpmn:categoryValue id="[^"]+" value="Phase 1"/)
  })

  it('verbindet Textanmerkung per Assoziation und Datenobjekte per Datenassoziation', async () => {
    const kit = await createKit()
    const task = kit.create('bpmn:Task', 400, 120)
    const note = kit.create('bpmn:TextAnnotation', 400, 300)
    const association = kit.modeling.connect(note, task)
    expect(association.type).toBe('bpmn:Association')
    const data = kit.create('bpmn:DataObjectReference', 250, 300)
    const input = kit.modeling.connect(data, task)
    expect(input.type).toBe('bpmn:DataInputAssociation')
    expect(getBusinessObject(task).dataInputAssociations).toContain(getBusinessObject(input))
    const store = kit.create('bpmn:DataStoreReference', 600, 300)
    const output = kit.modeling.connect(task, store)
    expect(output.type).toBe('bpmn:DataOutputAssociation')
    expect(getBusinessObject(output).targetRef).toBe(getBusinessObject(store))
    const xml = await kit.xml()
    expect(xml).toContain('<bpmn:dataInputAssociation')
    expect(xml).toContain('<bpmn:dataObject id=')
  })
})

describe('Modellierung: Ersetzen', () => {
  it('ersetzt Aufgabe durch Benutzeraufgabe unter Erhalt von Kennung, Name, Dokumentation und Erweiterungen', async () => {
    const kit = await createKit()
    const task = kit.create('bpmn:Task', 400, 120)
    const moddle = kit.editor.get<any>('moddle')
    const documentation = moddle.create('bpmn:Documentation', { text: 'Beschreibung' })
    kit.modeling.updateProperties(task, { name: 'Prüfen', documentation: [documentation] })
    getBusinessObject(task).$attrs['flowaudit:marke'] = 'x'
    kit.modeling.setColor([task], { fill: '#c8e6c9' })
    const start = kit.registry.get('StartEvent_1')
    kit.modeling.connect(start, task)
    const replaced = kit.replace.replaceElement(task, { type: 'bpmn:UserTask' })
    expect(replaced.id).toBe(task.id)
    const bo = getBusinessObject(replaced)
    expect(bo.$type).toBe('bpmn:UserTask')
    expect(bo.name).toBe('Prüfen')
    expect(bo.documentation[0].text).toBe('Beschreibung')
    expect(bo.$attrs['flowaudit:marke']).toBe('x')
    expect(replaced.di.get('bioc:fill')).toBe('#c8e6c9')
    expect(replaced.incoming.length).toBe(1)
    kit.commandStack.undo()
    expect(getBusinessObject(kit.registry.get(task.id)).$type).toBe('bpmn:Task')
  })

  it('ersetzt Ereignisse (Definitionen, Rand, unterbrechend) und Gateways', async () => {
    const kit = await createKit()
    const start = kit.registry.get('StartEvent_1')
    const timer = kit.replace.replaceElement(start, { type: 'bpmn:StartEvent', eventDefinitionType: 'bpmn:TimerEventDefinition' })
    expect(getBusinessObject(timer).eventDefinitions[0].$type).toBe('bpmn:TimerEventDefinition')
    const end = kit.replace.replaceElement(timer, { type: 'bpmn:EndEvent', eventDefinitionType: 'bpmn:TerminateEventDefinition' })
    expect(end.type).toBe('bpmn:EndEvent')
    const gateway = kit.create('bpmn:ExclusiveGateway', 400, 300)
    const eventBased = kit.replace.replaceElement(gateway, { type: 'bpmn:EventBasedGateway', eventGatewayType: 'Parallel', instantiate: true })
    expect(getBusinessObject(eventBased).eventGatewayType).toBe('Parallel')
    expect(getBusinessObject(eventBased).instantiate).toBe(true)
  })

  it('heftet Zwischenereignis an und löst es wieder (Rand ↔ Zwischen)', async () => {
    const kit = await createKit()
    const task = kit.create('bpmn:Task', 400, 120)
    const event = kit.elementFactory.createShape({ type: 'bpmn:IntermediateThrowEvent' })
    const boundary = kit.modeling.createShape(event, { x: task.x + 50, y: task.y + task.height }, task, { attach: true })
    expect(boundary.type).toBe('bpmn:BoundaryEvent')
    expect(boundary.host).toBe(task)
    expect(getBusinessObject(boundary).attachedToRef).toBe(getBusinessObject(task))
    kit.modeling.moveElements([boundary], { x: 0, y: 200 }, kit.root())
    const detached = kit.registry.get(boundary.id)
    expect(detached.type).toBe('bpmn:IntermediateCatchEvent')
    expect(detached.host).toBeFalsy()
  })

  it('klappt Teilprozess auf und zu (Inhalt wandert in eigene Ebene)', async () => {
    const kit = await createKit()
    const sub = kit.create('bpmn:SubProcess', 500, 300, undefined, { isExpanded: true })
    expect(sub.children.some((child: any) => child.type === 'bpmn:StartEvent')).toBe(true)
    const collapsed = kit.replace.replaceElement(sub, { type: 'bpmn:SubProcess', isExpanded: false })
    expect(collapsed.di.isExpanded).toBe(false)
    expect(collapsed.width).toBe(100)
    const planeRoot = kit.registry.get(`${collapsed.id}_plane`)
    expect(planeRoot.children.length).toBeGreaterThan(0)
    const xml = await kit.xml()
    expect(xml).toContain(`bpmnElement="${collapsed.id}"`)
    const expanded = kit.replace.replaceElement(collapsed, { type: 'bpmn:SubProcess', isExpanded: true })
    expect(expanded.children.some((child: any) => child.type === 'bpmn:StartEvent')).toBe(true)
    expect(kit.registry.get(`${collapsed.id}_plane`)).toBeUndefined()
    kit.commandStack.undo()
    expect(kit.registry.get(`${collapsed.id}_plane`)).toBeTruthy()
  })
})

describe('Modellierung: Pools und Bahnen', () => {
  it('erster Pool umschließt den Prozess und macht eine Kollaboration', async () => {
    const kit = await createKit()
    const process = getBusinessObject(kit.root())
    const participant = kit.create('bpmn:Participant', 400, 200, undefined, { isExpanded: true })
    const root = kit.root()
    expect(root.type === 'bpmn:Collaboration' || getBusinessObject(root).$type).toBe('bpmn:Collaboration')
    expect(getBusinessObject(participant).processRef).toBe(process)
    const start = kit.registry.get('StartEvent_1')
    expect(start.parent).toBe(participant)
    expect(start.x).toBeGreaterThan(participant.x)
    const xml = await kit.xml()
    expect(xml).toContain('<bpmn:collaboration')
    expect(xml).toContain(`processRef="${process.id}"`)
    kit.commandStack.undo()
    expect(getBusinessObject(kit.root()).$type).toBe('bpmn:Process')
    expect(kit.registry.get('StartEvent_1').parent).toBe(kit.root())
  })

  it('legt Bahnen an (oberhalb, unterhalb, geteilt) und pflegt flowNodeRef', async () => {
    const kit = await createKit()
    const participant = kit.create('bpmn:Participant', 400, 200, undefined, { isExpanded: true })
    const below = kit.modeling.addLane(participant, 'bottom')
    const lanes = participant.children.filter((child: any) => child.type === 'bpmn:Lane')
    expect(lanes.length).toBe(2)
    expect(participant.height).toBeGreaterThan(250)
    const [first, second] = lanes.sort((a: any, b: any) => a.y - b.y)
    expect(first.y + first.height).toBe(second.y)
    expect(below).toBe(second)
    const start = kit.registry.get('StartEvent_1')
    expect(getBusinessObject(first).flowNodeRef).toContain(getBusinessObject(start))
    kit.modeling.moveElements([start], { x: 0, y: second.y + 40 - start.y })
    expect(getBusinessObject(second).flowNodeRef).toContain(getBusinessObject(start))
    expect(getBusinessObject(first).flowNodeRef).not.toContain(getBusinessObject(start))
    const children = kit.modeling.splitLane(second, 3)
    expect(children.length).toBe(3)
    expect(getBusinessObject(second).childLaneSet.lanes.length).toBe(3)
    const above = kit.modeling.addLane(first, 'top')
    expect(above.y + above.height).toBe(first.y)
    expect(participant.y).toBe(above.y)
    const xml = await kit.xml()
    expect(xml).toContain('<bpmn:childLaneSet')
    expect(xml).toContain('<bpmn:flowNodeRef>StartEvent_1</bpmn:flowNodeRef>')
  })

  it('verteilt Platz beim Löschen einer Bahn und passt Bahnen bei Poolgröße an', async () => {
    const kit = await createKit()
    const participant = kit.create('bpmn:Participant', 400, 200, undefined, { isExpanded: true })
    kit.modeling.splitLane(participant, 3)
    const lanes = () => participant.children.filter((child: any) => child.type === 'bpmn:Lane').sort((a: any, b: any) => a.y - b.y)
    const [a, b, c] = lanes()
    kit.modeling.removeShape(b)
    expect(lanes().length).toBe(2)
    expect(a.y + a.height).toBe(c.y)
    kit.modeling.resizeShape(participant, { x: participant.x, y: participant.y, width: participant.width + 100, height: participant.height + 60 })
    for (const lane of lanes()) expect(lane.x + lane.width).toBe(participant.x + participant.width)
    const last = lanes()[1]
    expect(last.y + last.height).toBe(participant.y + participant.height)
  })

  it('ändert die Größe einer Bahn mit Nachbarn (lane.resize)', async () => {
    const kit = await createKit()
    const participant = kit.create('bpmn:Participant', 400, 200, undefined, { isExpanded: true })
    kit.modeling.splitLane(participant, 2)
    const [top, bottom] = participant.children.filter((child: any) => child.type === 'bpmn:Lane').sort((x: any, y: any) => x.y - y.y)
    const oldBottom = bottom.y
    kit.modeling.resizeLane(top, { x: top.x, y: top.y, width: top.width, height: top.height + 30 })
    expect(bottom.y).toBe(oldBottom + 30)
    expect(top.y + top.height).toBe(bottom.y)
  })

  it('verbindet Pools per Nachrichtenfluss und wechselt Flussart beim Verschieben', async () => {
    const kit = await createKit()
    const poolA = kit.create('bpmn:Participant', 400, 200, undefined, { isExpanded: true })
    const poolB = kit.create('bpmn:Participant', 400, 600, undefined, { isExpanded: true })
    const start = kit.registry.get('StartEvent_1')
    const taskB = kit.create('bpmn:Task', 400, 600, poolB)
    const message = kit.modeling.connect(taskB, start)
    expect(message.type).toBe('bpmn:MessageFlow')
    expect(getBusinessObject(kit.root()).messageFlows).toContain(getBusinessObject(message))
    const flowPool = kit.modeling.connect(poolA, poolB)
    expect(flowPool.type).toBe('bpmn:MessageFlow')
    // Nachrichtenfluss zum Startereignis entfällt beim Verschieben in Pool A
    // (Startereignisse haben keine eingehenden Sequenzflüsse), der zur
    // Aufgabe wird zum Sequenzfluss.
    const taskA = kit.create('bpmn:Task', 700, 200, poolA)
    kit.modeling.connect(taskB, taskA)
    kit.modeling.moveElements([taskB], { x: 150, y: poolA.y + 100 - taskB.y }, poolA)
    const connections = taskB.outgoing
    expect(connections.length).toBe(1)
    expect(connections[0].type).toBe('bpmn:SequenceFlow')
    expect(connections[0].target).toBe(taskA)
    expect(getBusinessObject(poolA).processRef.flowElements).toContain(getBusinessObject(connections[0]))
  })

  it('macht nach Löschen des letzten Pools wieder einen Prozess', async () => {
    const kit = await createKit()
    const participant = kit.create('bpmn:Participant', 400, 200, undefined, { isExpanded: true })
    kit.modeling.removeShape(participant)
    expect(getBusinessObject(kit.root()).$type).toBe('bpmn:Process')
    const xml = await kit.xml()
    expect(xml).not.toContain('<bpmn:collaboration')
  })

  it('ersetzt Pool durch leeren Pool und zurück', async () => {
    const kit = await createKit()
    const participant = kit.create('bpmn:Participant', 400, 200, undefined, { isExpanded: true })
    const empty = kit.replace.replaceElement(participant, { type: 'bpmn:Participant', isExpanded: false })
    expect(getBusinessObject(empty).processRef).toBeUndefined()
    expect(kit.registry.get('StartEvent_1')).toBeUndefined()
  })
})

describe('Modellierung: Ausrichten, Verteilen, Raumwerkzeug', () => {
  it('richtet aus und verteilt', async () => {
    const kit = await createKit()
    const a = kit.create('bpmn:Task', 300, 100)
    const b = kit.create('bpmn:Task', 500, 180)
    const c = kit.create('bpmn:Task', 900, 260)
    kit.editor.get<any>('alignElements').trigger([a, b, c], 'top')
    expect(b.y).toBe(a.y)
    expect(c.y).toBe(a.y)
    kit.editor.get<any>('distributeElements').trigger([a, b, c], 'horizontal')
    expect(Math.abs(b.x - a.x - (c.x - b.x))).toBeLessThanOrEqual(1)
  })

  it('schafft Platz mit dem Raumwerkzeug', async () => {
    const kit = await createKit()
    const task = kit.create('bpmn:Task', 400, 120)
    const oldX = task.x
    kit.modeling.createSpace([task], [], { x: 100, y: 0 }, 'e', 300)
    expect(task.x).toBe(oldX + 100)
    expect(task.di.bounds.x).toBe(oldX + 100)
  })
})
